---
title: "2 turno em São Paulo"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(extrafont)
library(hrbrthemes)


#bases
vereadores <- read_rds('vereadores.rds')

estado <- read_rds('estado.rds')


#arrumar
munisp <- estado %>%
  filter(NM_MUNICIPIO == 'SÃO PAULO')

vereadores <- vereadores %>%
  filter(DS_CARGO == 'Vereador')

#branco e nulo ----------------
#pegar brancos e nulos
branconulo <- munisp %>%
  filter(NM_VOTAVEL == 'Branco'|
           NM_VOTAVEL == 'Nulo') %>%
  group_by(NR_ZONA) %>%
  summarize(sum(QT_VOTOS))

#mudar nome para ficar igual ao shp
branconulo <- branconulo %>%
  rename(ZEFINAL = NR_ZONA)

#abstencao ---------------------------------
abst <- munisp %>%
  group_by(NR_SECAO, NR_ZONA) %>%
  summarize(QT_ABSTENCOES) %>%
  distinct(NR_SECAO, .keep_all = TRUE)

abst <- abst %>%
  group_by(NR_ZONA) %>%
  summarize(sum(QT_ABSTENCOES))

abst <- abst %>%
  rename(ZEFINAL = NR_ZONA)

#laranjas ---------------------------------
vereadoresvotos <- vereadores %>%
  group_by(NM_URNA_CANDIDATO, NM_MUNICIPIO, SG_PARTIDO, DS_SITUACAO_CANDIDATURA,
           DS_DETALHE_SITUACAO_CAND) %>%
  summarize(votos = sum(QT_VOTOS_NOMINAIS))

laranja <- vereadoresvotos %>%
  filter(votos == 0) %>%
  ungroup()


#vereadores sp  eleitos ------------
vereadores_eleitos_capital_TUDO <- vereadores %>%
  filter(NM_MUNICIPIO == 'SÃO PAULO') %>%
  filter(DS_SIT_TOT_TURNO != 'SUPLENTE',
        DS_SIT_TOT_TURNO != 'NÃO ELEITO') %>%
  rename(ZEFINAL = NR_ZONA)

vereadores_eleitos_capital <-   vereadores_eleitos_capital_TUDO %>%
  group_by(NM_URNA_CANDIDATO, 
                                         NM_MUNICIPIO, SG_PARTIDO, 
                                         DS_SITUACAO_CANDIDATURA,
                                         DS_DETALHE_SITUACAO_CAND) %>%
  summarize(votos = sum(QT_VOTOS_NOMINAIS)) %>%
  ungroup()

#Mapas -----------------------
#abrir shape do estado
library(rgdal)

shape <- readOGR(dsn = ".", layer = "ZONAS_FINAL")

#mudar formato
library(sf)

capital <-st_as_sf(shape)

#arrumar encoding e separar dado
capital <- capital %>%
  mutate(FIRST_sede = iconv(FIRST_sede, 'UTF-8', 'latin1'),
         FIRST_NOME = iconv(FIRST_NOME, 'UTF-8', 'latin1')) %>%
  separate(FIRST_NOME, into = c('MUN', "ZONA"), sep = "-")

#filtrar para capital
capital <- capital %>%
  filter(MUN == 'SÃO PAULO ')
```



Brancos Nulos e Abstenções 2 turno
==================================================


Column {data-width=500}
-------------------------------------

### Total de brancos e nulos {.value-box}

```{r}
branco_total <- sum(branconulo$`sum(QT_VOTOS)`)
valueBox(branco_total, icon = 'fa-sticky-note')
```

### Total de abstenções {.value-box}

```{r}
abst_total <- sum(abst$`sum(QT_ABSTENCOES)`)
valueBox(abst_total, icon = 'fa-times-circle' )
```

### Votos

```{r}
library(plotly)

prefvotos_total <- estado %>% 
  filter(NM_MUNICIPIO == 'SÃO PAULO') %>% 
  group_by(NM_VOTAVEL) %>%
  summarize(votos = sum(QT_VOTOS)) %>%
  ungroup()


p <- prefvotos_total %>%
  ggplot(aes(NM_VOTAVEL, votos)) +
  geom_col(fill = "#007f5f") +
  coord_flip() +
  theme_minimal() +
  labs(x="", y = "Total de votos", title = "Resultado das eleições")

ggplotly(p)
```



Column {data-width=500}  {.tabset}
-------------------------------------


### Ganhador por zona pref
```{r, message=FALSE, warning=FALSE}
# quem ganhou por zona boulos e covas
prefvotos <- estado %>% 
  filter(NM_MUNICIPIO == 'SÃO PAULO') %>% 
  group_by(NR_ZONA, NM_VOTAVEL) %>%
  summarize(votos = sum(QT_VOTOS)) %>%
  ungroup()

ganhador <- prefvotos %>%
  group_by(NR_ZONA) %>% 
  pivot_wider(NR_ZONA, names_from = NM_VOTAVEL, values_from = votos)

ganhador <- ganhador %>% 
  mutate(ganhador = case_when(`GUILHERME BOULOS` > `BRUNO COVAS` ~ 'Boulos',
                              TRUE ~ 'Covas'),
         votos_ganhador = case_when(`GUILHERME BOULOS` > `BRUNO COVAS` ~ `GUILHERME BOULOS`,
                              TRUE ~ `BRUNO COVAS`)) %>% 
  select(NR_ZONA, ganhador, votos_ganhador) %>% 
  rename(ZEFINAL = NR_ZONA)

ganhadormapa <- left_join(capital, ganhador)



#cores
pal <- colorFactor(c("#2d00f7","#00b4d8"), ganhadormapa$ganhador)

pal <- colorFactor(topo.colors(2), ganhadormapa$ganhador)


#adicionar dados
labels <- sprintf(
  "<strong>%s</strong><br/>%g votos</sup>",
  ganhadormapa$ganhador, ganhadormapa$votos_ganhador
) %>% lapply(htmltools::HTML)

#mapa
mapaganhador <- leaflet(ganhadormapa) %>%
  addPolygons(
    fillColor = ~pal(ganhador),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))


mapaganhador %>%
  addLegend(pal = pal, values = ~ganhador, opacity = 0.7, title = NULL,
            position = "bottomright")
```

### Brancos e Nulos no segundo turno

```{r, message=FALSE, warning=FALSE}
#SEGUNDO TURNO 2020 ------------------------------------------------------------
brancomapa <- left_join(capital, branconulo)

#cores
pal <- colorBin("Greens", domain = brancomapa$`sum(QT_VOTOS)`)

#adicionar dados
labels <- sprintf(
  "<strong>%s</strong><br/>%g brancos e nulos</sup>",
  brancomapa$ZONA, brancomapa$`sum(QT_VOTOS)`
) %>% lapply(htmltools::HTML)

#mapa
mapabrancos <- leaflet(brancomapa) %>%
  addPolygons(
    fillColor = ~pal(`sum(QT_VOTOS)`),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))


mapabrancos %>%
  addLegend(pal = pal, values = ~`sum(QT_VOTOS)`, opacity = 0.7, title = NULL,
            position = "bottomright")

```


### Abstenções no segundo turno

```{r, message=FALSE, warning=FALSE}
abstmapa <- left_join(capital, abst)

#cores
pal <- colorBin("Greens", domain = abst$`sum(QT_ABSTENCOES)`)

#adicionar dados
labels <- sprintf(
  "<strong>%s</strong><br/>%g abstenções</sup>",
  abstmapa$ZONA, abstmapa$`sum(QT_ABSTENCOES)`
) %>% lapply(htmltools::HTML)

#mapa
abstmapa <- leaflet(abstmapa) %>%
  addPolygons(
    fillColor = ~pal(`sum(QT_ABSTENCOES)`),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))


abstmapa %>%
  addLegend(pal = pal, values = ~`sum(QT_ABSTENCOES)`, opacity = 0.7, title = NULL,
            position = "bottomright")
```


Câmara de São Paulo
=================================

Column {data-width=400} {.tabset}
-------------------------------------

### Partidos Eleitos

```{r, warning=FALSE, message=FALSE}
vereadores_eleitos_capital %>%
  count(SG_PARTIDO, sort = TRUE) %>%
  mutate(SG_PARTIDO = fct_reorder(SG_PARTIDO, n)) %>%
  ggplot(aes(SG_PARTIDO, n)) +
  geom_col(fill = "#2b9348") +
  coord_flip() +
  theme_ipsum_tw() +
  labs(x = "", y = "", title = "Partidos na Câmara")
  
```


### Mais votados
```{r, warning=FALSE, message=FALSE}
vereadores_eleitos_capital %>%
  top_n(10,votos) %>%
  mutate(NM_URNA_CANDIDATO = fct_reorder(NM_URNA_CANDIDATO, votos)) %>%
  ggplot(aes(NM_URNA_CANDIDATO, votos)) +
  geom_bar(stat = 'identity', fill = "#2b9348") +
  coord_flip() +
  theme_ipsum_tw() +
  labs(x = "", y = "Total de votos", title = "Candidatos mais votados")
```


Column {data-width=600}  {.tabset}
-------------------------------------


### Ganhadores por zona
```{r, warning=FALSE, message=FALSE}
vereadores_eleitos_capital_TUDO <- vereadores %>%
  filter(NM_MUNICIPIO == 'SÃO PAULO') %>%
  filter(DS_SIT_TOT_TURNO != 'SUPLENTE',
         DS_SIT_TOT_TURNO != 'NÃO ELEITO') %>%
  rename(ZEFINAL = NR_ZONA)

verezonas <-   vereadores_eleitos_capital_TUDO %>%
  group_by(SG_PARTIDO, 
           ZEFINAL) %>%
  summarize(votos = sum(QT_VOTOS_NOMINAIS)) %>%
  ungroup()


ganhador_vereador <- verezonas %>%
  group_by(ZEFINAL) %>% 
  pivot_wider(ZEFINAL, names_from = SG_PARTIDO, values_from = votos)

library(readxl)
ganhador_vereador <- read_excel('ganhador_vereador.xlsx')

ganhadormapa_vereador <- left_join(capital, ganhador_vereador)



#cores

pal <- colorFactor('Paired', ganhadormapa_vereador$ganhador)


#adicionar dados
labels <- sprintf(
  "<strong>%s</strong><br/>%g votos </sup>",
  ganhadormapa_vereador$ganhador, ganhadormapa_vereador$votos
) %>% lapply(htmltools::HTML)

#mapa
mapaganhador_vereador <- leaflet(ganhadormapa_vereador) %>%
  addPolygons(
    fillColor = ~pal(ganhador),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))


mapaganhador_vereador %>%
  addLegend(pal = pal, values = ~ganhador, opacity = 0.7, title = NULL,
            position = "bottomright")

```



### Centrão
```{r, warning=FALSE, message=FALSE}
centrao <- vereadores_eleitos_capital_TUDO %>%
  filter(SG_PARTIDO != 'PT',
         SG_PARTIDO != 'PSDB',
         SG_PARTIDO != 'NOVO',
         SG_PARTIDO != 'PSOL',
         SG_PARTIDO != 'PSL',
         SG_PARTIDO != 'PSB') %>%
  group_by(ZEFINAL) %>%
  summarize(sum(QT_VOTOS_NOMINAIS))

centraomapa <- left_join(capital, centrao)


#adicionar dados
labels <- sprintf(
  "<strong>%s</strong><br/>%g votos</sup>",
  centraomapa$ZONA, centraomapa$`sum(QT_VOTOS_NOMINAIS)`
) %>% lapply(htmltools::HTML)

#cores
pal <- colorBin("Greens", domain = centraomapa$`sum(QT_VOTOS_NOMINAIS)`)

#mapa
mapacentrao <- leaflet(centraomapa) %>%
  addPolygons(
    fillColor = ~pal(`sum(QT_VOTOS_NOMINAIS)`),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))


mapacentrao %>%
  addLegend(pal = pal, values = ~`sum(QT_VOTOS_NOMINAIS)`, opacity = 0.7, title = NULL,
            position = "bottomright")
```


### NOVO
```{r, warning=FALSE, message=FALSE}
novo <- vereadores_eleitos_capital_TUDO %>%
  filter(SG_PARTIDO == 'NOVO') %>%
  group_by(ZEFINAL) %>%
  summarize(sum(QT_VOTOS_NOMINAIS))

novomapa <- left_join(capital, novo)


#adicionar dados
labels <- sprintf(
  "<strong>%s</strong><br/>%g votos</sup>",
  novomapa$ZONA, novomapa$`sum(QT_VOTOS_NOMINAIS)`
) %>% lapply(htmltools::HTML)

#cores
pal <- colorBin("Greens", domain = novomapa$`sum(QT_VOTOS_NOMINAIS)`)

#mapa
mapanovo <- leaflet(novomapa) %>%
  addPolygons(
    fillColor = ~pal(`sum(QT_VOTOS_NOMINAIS)`),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))


mapanovo %>%
  addLegend(pal = pal, values = ~`sum(QT_VOTOS_NOMINAIS)`, opacity = 0.7, title = NULL,
            position = "bottomright")
```


### PSOL
```{r, warning=FALSE, message=FALSE}
psol <- vereadores_eleitos_capital_TUDO %>%
  filter(SG_PARTIDO == 'PSOL') %>%
  group_by(ZEFINAL) %>%
  summarize(sum(QT_VOTOS_NOMINAIS))

psolmapa <- left_join(capital, psol)


#adicionar dados
labels <- sprintf(
  "<strong>%s</strong><br/>%g votos</sup>",
  psolmapa$ZONA, psolmapa$`sum(QT_VOTOS_NOMINAIS)`
) %>% lapply(htmltools::HTML)

#cores
pal <- colorBin("Greens", domain = psolmapa$`sum(QT_VOTOS_NOMINAIS)`)

#mapa
mapapsol <- leaflet(psolmapa) %>%
  addPolygons(
    fillColor = ~pal(`sum(QT_VOTOS_NOMINAIS)`),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))


mapapsol %>%
  addLegend(pal = pal, values = ~`sum(QT_VOTOS_NOMINAIS)`, opacity = 0.7, title = NULL,
            position = "bottomright")
```



### PT
```{r, warning=FALSE, message=FALSE}
pt <- vereadores_eleitos_capital_TUDO %>%
  filter(SG_PARTIDO == 'PT') %>%
  group_by(ZEFINAL) %>%
  summarize(sum(QT_VOTOS_NOMINAIS))

ptmapa <- left_join(capital, pt)

#adicionar dados
labels <- sprintf(
  "<strong>%s</strong><br/>%g votos</sup>",
  ptmapa$ZONA, ptmapa$`sum(QT_VOTOS_NOMINAIS)`
) %>% lapply(htmltools::HTML)

#cores
pal <- colorBin("Greens", domain = ptmapa$`sum(QT_VOTOS_NOMINAIS)`)

#mapa
mapapt <- leaflet(ptmapa) %>%
  addPolygons(
    fillColor = ~pal(`sum(QT_VOTOS_NOMINAIS)`),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))


mapapt %>%
  addLegend(pal = pal, values = ~`sum(QT_VOTOS_NOMINAIS)`, opacity = 0.7, title = NULL,
            position = "bottomright")
```



### PSDB
```{r, warning=FALSE, message=FALSE}
psdb <- vereadores_eleitos_capital_TUDO %>%
  filter(SG_PARTIDO == 'PSDB') %>%
  group_by(ZEFINAL) %>%
  summarize(sum(QT_VOTOS_NOMINAIS))

psdbmapa <- left_join(capital, psdb)


#adicionar dados
labels <- sprintf(
  "<strong>%s</strong><br/>%g votos</sup>",
  psdbmapa$ZONA, psdbmapa$`sum(QT_VOTOS_NOMINAIS)`
) %>% lapply(htmltools::HTML)

#cores
pal <- colorBin("Greens", domain = psdbmapa$`sum(QT_VOTOS_NOMINAIS)`)

#mapa
mapapsdb <- leaflet(psdbmapa) %>%
  addPolygons(
    fillColor = ~pal(`sum(QT_VOTOS_NOMINAIS)`),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))


mapapsdb %>%
  addLegend(pal = pal, values = ~`sum(QT_VOTOS_NOMINAIS)`, opacity = 0.7, title = NULL,
            position = "bottomright")
```


Possíveis Laranjas - vereadores
============================================

Column {data-width=600} {.tabset}
-------------------------------------

### Municípios

```{r, warning=FALSE, message=FALSE}
laranja %>%
  count(NM_MUNICIPIO) %>%
  top_n(15, n) %>%
  mutate(NM_MUNICIPIO = fct_reorder(NM_MUNICIPIO, n)) %>%
  ggplot(aes(NM_MUNICIPIO, n)) +
  geom_col(fill = "#007f5f") +
  coord_flip() +
  theme_ipsum_tw() +
  labs(x = "", y ="Contagem de municípios", title = "Principais municípios",
       subtitle = "Municípios com candidatos deferidos e aptos com voto nominal igual a zero")
```

### Partidos
```{r, warning=FALSE, message=FALSE}
laranja %>%
  count(SG_PARTIDO) %>%
  top_n(15, n) %>%
  mutate(SG_PARTIDO = fct_reorder(SG_PARTIDO, n)) %>%
  ggplot(aes(SG_PARTIDO, n)) +
  geom_col(fill = "#007f5f") +
  coord_flip() +
  theme_ipsum_tw() +
  labs(x="", y = "Contagem de partidos", title = "Partidos com potenciais laranjas", subtitle = "Partidos que possuem candidatos com votos nominais igual a zero")
```


Column {data-width=400}
-------------------------------------

### Gênero dos candidatos com nenhum voto nominal
```{r, warning=FALSE, message=FALSE}
laranja <- laranja %>%
  mutate(genero = genderBR::get_gender(NM_URNA_CANDIDATO))


laranja %>%
  ggplot(aes(genero)) +
  geom_bar(fill = '#007f5f') +
  theme_ipsum_tw() +
  labs(x = "", y = "Total de candidatos", title = "Gênero dos potenciais laranjas", subtitle = "Candidatos deferidos e aptos com voto nominal igual a zero")
```

